name: Deploy Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Install dependencies
        run: |
          pnpm install
          pnpm i -g wrangler
          sudo apt-get update && sudo apt-get install -y jq

      - name: Publish
        run: |
          cd packages/status-worker/
          [ -z ${{secrets.SECRET_SLACK_WEBHOOK_URL}} ] && echo ${{secrets.SECRET_SLACK_WEBHOOK_URL}} | npx wrangler secret put "SECRET_SLACK_WEBHOOK_URL"
          [ -z ${{secrets.SECRET_TELEGRAM_API_TOKEN}} ] && echo ${{secrets.SECRET_TELEGRAM_API_TOKEN}} | npx wrangler secret put "SECRET_TELEGRAM_API_TOKEN"
          [ -z ${{secrets.SECRET_TELEGRAM_CHAT_ID}} ] && echo ${{secrets.SECRET_TELEGRAM_CHAT_ID}} | npx wrangler secret put "SECRET_TELEGRAM_CHAT_ID"
          [ -z ${{secrets.SECRET_DISCORD_WEBHOOK_URL}} ] && echo ${{secrets.SECRET_DISCORD_WEBHOOK_URL}} | npx wrangler secret put "SECRET_DISCORD_WEBHOOK_URL"
          export KV_NAMESPACE_ID=5d308613ecd148bfa0ee7febb6d03b22
          echo "kv_namespaces = [{binding=\"KV_STATUS_PAGE\", id=\"${KV_NAMESPACE_ID}\"}]" >> wrangler.toml
          echo "[triggers]" >> wrangler.toml
          echo "crons = [\"*/5 * * * *\"]" >> wrangler.toml
          wrangler publish
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}